// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqJgH1nXKhV5QDNbWC8Tm987DusxOZHCQ',
    appId: '1:810245578711:web:7c5439f08ecf0aca38b592',
    messagingSenderId: '810245578711',
    projectId: 'cce-106-project',
    authDomain: 'cce-106-project.firebaseapp.com',
    storageBucket: 'cce-106-project.firebasestorage.app',
    measurementId: 'G-L1N9P74DB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp-rXv2v_vorNdqHJsp0RuMePXjDj3gYs',
    appId: '1:810245578711:android:60b643a782927c2038b592',
    messagingSenderId: '810245578711',
    projectId: 'cce-106-project',
    storageBucket: 'cce-106-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbXI0DKbGuOyM7QfQ3SleUWXJ_htAg5_k',
    appId: '1:810245578711:ios:0fb6607b6ff8fd6138b592',
    messagingSenderId: '810245578711',
    projectId: 'cce-106-project',
    storageBucket: 'cce-106-project.firebasestorage.app',
    iosBundleId: 'com.example.cce106FinanceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbXI0DKbGuOyM7QfQ3SleUWXJ_htAg5_k',
    appId: '1:810245578711:ios:0fb6607b6ff8fd6138b592',
    messagingSenderId: '810245578711',
    projectId: 'cce-106-project',
    storageBucket: 'cce-106-project.firebasestorage.app',
    iosBundleId: 'com.example.cce106FinanceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqJgH1nXKhV5QDNbWC8Tm987DusxOZHCQ',
    appId: '1:810245578711:web:54c88e5e31f3a35f38b592',
    messagingSenderId: '810245578711',
    projectId: 'cce-106-project',
    authDomain: 'cce-106-project.firebaseapp.com',
    storageBucket: 'cce-106-project.firebasestorage.app',
    measurementId: 'G-G82DVGHR3G',
  );

}