// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwNS-s8dKj3PAoQ2R_fuzXkMi3hjHSIZ4',
    appId: '1:990335661569:web:d76918671f1e142551f200',
    messagingSenderId: '990335661569',
    projectId: 'cce106proj',
    authDomain: 'cce106proj.firebaseapp.com',
    storageBucket: 'cce106proj.firebasestorage.app',
    measurementId: 'G-J74FKWF3ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBppp7DbTDGuOwNIYMyYFViamTYAte2rmc',
    appId: '1:990335661569:android:10a38d664c425fd051f200',
    messagingSenderId: '990335661569',
    projectId: 'cce106proj',
    storageBucket: 'cce106proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdf2twPGgBKfED6kxFIGfOMCKTswZeAxs',
    appId: '1:990335661569:ios:bee7d8e1b19c095a51f200',
    messagingSenderId: '990335661569',
    projectId: 'cce106proj',
    storageBucket: 'cce106proj.firebasestorage.app',
    iosBundleId: 'com.example.cce106FinanceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdf2twPGgBKfED6kxFIGfOMCKTswZeAxs',
    appId: '1:990335661569:ios:bee7d8e1b19c095a51f200',
    messagingSenderId: '990335661569',
    projectId: 'cce106proj',
    storageBucket: 'cce106proj.firebasestorage.app',
    iosBundleId: 'com.example.cce106FinanceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwNS-s8dKj3PAoQ2R_fuzXkMi3hjHSIZ4',
    appId: '1:990335661569:web:3c78a0e9950129dc51f200',
    messagingSenderId: '990335661569',
    projectId: 'cce106proj',
    authDomain: 'cce106proj.firebaseapp.com',
    storageBucket: 'cce106proj.firebasestorage.app',
    measurementId: 'G-68PXC4VJJP',
  );

}