import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'UI/theme.dart';
import 'auth/login.dart';
import 'firebase_options.dart'; // Ensure this file exists (auto-generated by FlutterFire CLI)

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // This uses your file!
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Finance Planner',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        scaffoldBackgroundColor: AppTheme.primary,
        fontFamily: 'Roboto',
        colorScheme: ColorScheme(
          brightness: Brightness.light,
          primary: AppTheme.accent,
          onPrimary: Colors.white,
          secondary: AppTheme.highlight,
          onSecondary: AppTheme.textPrimary,
          error: AppTheme.negative,
          onError: Colors.white,
          surface: AppTheme.surfaceLight,
          onSurface: AppTheme.textPrimary,
        ),
        useMaterial3: true,
        textTheme: TextTheme(
          bodyLarge: AppTheme.body,
          bodyMedium: AppTheme.body,
          titleLarge: AppTheme.heading,
          titleMedium: AppTheme.subheading,
        ),
      ),
      home: const LoginPage(),
    );
  }
}
